### ISSUE TITLE
init-script for puppet-dashboard-workers not working as expected

### ISSUE THREAD

**Issue by kimjohansen** [sodabrew/puppet-dashboard#275]
the init-script (redhat) for puppet-dashboard-workers not working as expected.

```
/etc/init.d/puppet-dashboard-workers start
Starting puppet-dashboard-workers: /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/paths.rb:205:in `chdir': Permission denied - /root (Errno::EACCES)
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/paths.rb:205:in `expand_dir'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/paths.rb:161:in `expanded'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/paths.rb:156:in `each'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/paths.rb:156:in `expanded'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/paths.rb:190:in `existent'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/paths.rb:93:in `filter_by'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/paths.rb:91:in `each'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/paths.rb:91:in `filter_by'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/paths.rb:76:in `eager_load'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/engine/configuration.rb:72:in `eager_load_paths'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/engine.rb:655:in `_all_autoload_paths'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/engine.rb:659:in `_all_load_paths'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/engine.rb:530
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/initializable.rb:30:in `instance_exec'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/initializable.rb:30:in `run'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/initializable.rb:55:in `run_initializers'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/initializable.rb:54:in `each'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/initializable.rb:54:in `run_initializers'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/application.rb:136:in `initialize!'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/railtie/configurable.rb:30:in `send'
    from /usr/share/puppet-dashboard/vendor/bundle/ruby/1.8/gems/railties-3.2.16/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /usr/share/puppet-dashboard/config/environment.rb:5
    from /usr/share/puppet-dashboard/script/delayed_job:3:in `require'
    from /usr/share/puppet-dashboard/script/delayed_job:3
```

workaround:

cd /tmp
/etc/init.d/puppet-dashboard-workers start

**Comment by bwitt** [comment]
Hi @kimjohansen there's been a bunch of changes recently that should address this sort of thing so please check against the latest version and if this is still an issue please reopen!
