### ISSUE TITLE
Installation issue on CentOS 7 (cannot find Rails)

### ISSUE THREAD

**Issue by tszym** [sodabrew/puppet-dashboard#325]
Hi there,

I tried to install the *Dashboard 2.0 - Beta 2* pre-release, but I am stuck with a Rails/Rake issue.
Not a ruby guy, I tried to search how to solve this, but I may have been too case-specific, and didn't found the solution.

I followed the steps provided in the README and changed the config files.

First successful part:
```
[me@centos]$ gem install bundler
Successfully installed bundler-1.10.6
Parsing documentation for bundler-1.10.6
1 gem installed

[me@centos]$ bundle install --deployment
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing rake 0.9.6
Installing i18n 0.6.9
Installing multi_json 1.8.2
Installing activesupport 3.2.16
Installing builder 3.0.4
Installing activemodel 3.2.16
Installing erubis 2.7.0
Installing journey 1.0.4
Installing rack 1.4.5
Installing rack-cache 1.2
Installing rack-test 0.6.2
Installing hike 1.2.3
Installing tilt 1.4.1
Installing sprockets 2.2.2
Installing actionpack 3.2.16
Installing mime-types 1.25.1
Installing polyglot 0.3.3
Installing treetop 1.4.15
Installing mail 2.5.4
Installing actionmailer 3.2.16
Installing arel 3.0.3
Installing tzinfo 0.3.38
Installing activerecord 3.2.16
Installing activeresource 3.2.16
Installing metaclass 0.0.1
Installing mocha 0.13.3
Installing bourne 1.5.0
Installing daemons 1.1.9
Installing delayed_job 3.0.5
Installing delayed_job_active_record 0.3.3
Installing diff-lcs 1.2.5
Installing eventmachine 1.0.3 with native extensions
Installing execjs 2.0.2
Installing factory_girl 2.6.4
Installing haml 3.1.8
Installing rack-ssl 1.3.3
Installing json 1.8.1 with native extensions
Installing rdoc 3.12.2
Installing thor 0.18.1
Installing railties 3.2.16
Installing haml-rails 0.3.5
Installing has_scope 0.5.1
Installing responders 0.9.3
Installing inherited_resources 1.4.0
Installing jquery-rails 2.3.0
Installing json_pure 1.8.1
Installing mysql2 0.3.14 with native extensions
Installing nokogiri 1.5.11 with native extensions
Installing pg 0.17.1 with native extensions
Using bundler 1.10.6
Installing rails 3.2.16
Installing rspec-core 2.13.1
Installing rspec-expectations 2.13.0
Installing rspec-mocks 2.13.1
Installing rspec 2.13.0
Installing rspec-html-matchers 0.4.3
Installing rspec-rails 2.13.2
Installing safe_yaml 1.0.0
Installing sass 3.2.13
Installing sass-rails 3.2.6
Installing shoulda-matchers 1.5.6
Installing sqlite3 1.3.8 with native extensions
Installing thin 1.6.1 with native extensions
Installing timeline_fu 0.3.0
Installing uglifier 1.3.0
Installing will_paginate 3.0.5
Bundle complete! 29 Gemfile dependencies, 66 gems now installed.
Bundled gems are installed into ./vendor/bundle.
Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install
>= 1.9.2 : nothing to do! Yay!
```

Then the problems:
```
[me@centos]$ echo "secret_token: '$(bundle exec rake secret)'" >> config/settings.yml
Warning: Rails rake tasks currently unavailable because we can't find the 'rails' gem
rake aborted!
Don't know how to build task 'secret'

(See full trace by running task with --trace)
```

Ok, let's trace:
```
[me@centos]$  bundle exec rake secret --trace
Warning: Rails rake tasks currently unavailable because we can't find the 'rails' gem
rake aborted!
Don't know how to build task 'secret'

/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/gems/rake-0.9.6/lib/rake/task_manager.rb:49:in `[]'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/gems/rake-0.9.6/lib/rake/application.rb:142:in `invoke_task'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/gems/rake-0.9.6/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/gems/rake-0.9.6/lib/rake/application.rb:101:in `each'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/gems/rake-0.9.6/lib/rake/application.rb:101:in `block in top_level'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/gems/rake-0.9.6/lib/rake/application.rb:110:in `run_with_threads'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/gems/rake-0.9.6/lib/rake/application.rb:95:in `top_level'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/gems/rake-0.9.6/lib/rake/application.rb:73:in `block in run'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/gems/rake-0.9.6/lib/rake/application.rb:160:in `standard_exception_handling'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/gems/rake-0.9.6/lib/rake/application.rb:70:in `run'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/gems/rake-0.9.6/bin/rake:37:in `<top (required)>'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/bin/rake:23:in `load'
/srv/puppet-dashboard-2.0.0-beta2/vendor/bundle/ruby/bin/rake:23:in `<main>'
```

The issue and the trace are the same for `$ bundle exec rake db:setup`, so I am stuck here in the installation.

Additional details:
```
[me@centos]$  which ruby
/usr/bin/ruby
[me@centos]$ ruby --version
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
[me@centos]$ which bundle
/usr/local/bin/bundle
[me@centos]$ bundle --version
Bundler version 1.10.6
[me@centos]$ which rake
/usr/local/bin/rake
[me@centos]$ rake --version
rake, version 10.4.2
```

And the things I had to install to get `bundle install` installing all the things:
`# yum install rubygem-bundler ruby-devel gcc gcc-c++ {mariadb,libxml2,libxslt,postgresql,sqlite}-devel nodejs`

Hope you can help me on this.

Regards

**Comment by jorhett** [comment]
Try adding RAILS_ENV=production to the command line ;)

**Comment by tszym** [comment]
It works pretty well with this.

Thanks for your help! :)
