### ISSUE TITLE
Installation on RHEL 7.5

### ISSUE THREAD

**Issue by unixman99** [sodabrew/puppet-dashboard#381]
hi, I managed to get this to run on rhel 7.5 but the data going in just doesn't show up, I see 100's pending tasks stacking up, so I know the data is definitely getting there.  Is there something else i'm missing?  I notice there's no script/delayed_job anymore.  any help is much appreciated, thanks!

Had to do it like this, since there is no yarn for rhel, and db:setup gives an error about some field types that don't match:
bundle exec rake db:drop RAILS_ENV=production
bundle exec rake db:create RAILS_ENV=production
bundle exec rake db:migrate RAILS_ENV=production

$ export SECRET_KEY_BASE=$(bundle exec rails secret)

$ RAILS_ENV=production bundle exec rails server
=> Booting Thin
=> Rails 5.2.0 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:3000, CTRL+C to stop

**Comment by bwitt** [comment]
Sounds like you don't have the workers running; there's a systemd config file at
https://github.com/sodabrew/puppet-dashboard/blob/master/ext/redhat/puppet-dashboard-workers.service
does that help if you set that up?

The docs are at 
https://github.com/sodabrew/puppet-dashboard/blob/master/docs/manual/1.2/bootstrapping.markdown#starting-and-managing-delayed-job-workers
but they appear to be out of date (they mention `A future version of Dashboard will ship with init scripts which will let you manage the workers with Puppet or your platform's service tools` which is incorrect)

btw you can get yarn for RHEL here:  
https://yarnpkg.com/en/docs/install#centos-stable

and what error did `db:setup` give you?

**Comment by unixman99** [comment]
ok, I see the workers running helped, I just hadn't seen it from the main instruction page. thx.  
As for the DB setup errors, I tried again just to confirm and it still exists:


$ RAILS_ENV=production bundle exec rake db:setup
(in /usr/share/puppet-dashboard)
Database 'dashboard' already exists
-- enable_extension("plpgsql")
   -> 0.0007s
-- create_table("delayed_job_failures", {:id=>:serial, :force=>:cascade})
   -> 0.0042s
-- create_table("delayed_jobs", {:id=>:serial, :force=>:cascade})
   -> 0.0025s
-- create_table("metrics", {:id=>:serial, :force=>:cascade})
   -> 0.0020s
-- create_table("node_class_memberships", {:id=>:serial, :force=>:cascade})
   -> 0.0025s
-- create_table("node_classes", {:id=>:serial, :force=>:cascade})
   -> 0.0013s
-- create_table("node_group_class_memberships", {:id=>:serial, :force=>:cascade})
   -> 0.0019s
-- create_table("node_group_edges", {:id=>:serial, :force=>:cascade})
   -> 0.0019s
-- create_table("node_group_memberships", {:id=>:serial, :force=>:cascade})
   -> 0.0019s
-- create_table("node_groups", {:id=>:serial, :force=>:cascade})
   -> 0.0013s
-- create_table("nodes", {:id=>:serial, :force=>:cascade})
   -> 0.0021s
-- create_table("old_reports", {:id=>:serial, :force=>:cascade})
   -> 0.0013s
-- create_table("parameters", {:id=>:serial, :force=>:cascade})
   -> 0.0019s
-- create_table("report_logs", {:id=>:serial, :force=>:cascade})
   -> 0.0017s
-- create_table("reports", {:id=>:serial, :force=>:cascade})
   -> 0.0025s
-- create_table("resource_events", {:id=>:serial, :force=>:cascade})
   -> 0.0019s
-- create_table("resource_statuses", {:id=>:serial, :force=>:cascade})
   -> 0.0021s
-- create_table("timeline_events", {:id=>:serial, :force=>:cascade})
   -> 0.0021s
-- add_foreign_key("metrics", "reports", {:name=>"fk_metrics_report_id", :on_delete=>:cascade})
rake aborted!
ActiveRecord::MismatchedForeignKey: Column `report_id` on table `metrics` has a type of `int(11)`.
This does not match column `id` on `reports`, which has type `bigint(20) unsigned`.
To resolve this issue, change the type of the `report_id` column on `metrics` to be :integer. (For example `t.integer report_id`).

Original message: Mysql2::Error: Can't create table 'dashboard.#sql-59c_5' (errno: 150): ALTER TABLE `metrics` ADD CONSTRAINT `fk_metrics_report_id`
FOREIGN KEY (`report_id`)
  REFERENCES `reports` (`id`)
 ON DELETE CASCADE
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `_query'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `block in query'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `handle_interrupt'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `query'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:976:in `add_foreign_key'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:871:in `block in method_missing'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `block in say_with_time'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `say_with_time'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:860:in `method_missing'
/usr/share/puppet-dashboard/db/schema.rb:221:in `block in <top (required)>'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/schema.rb:50:in `instance_eval'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/schema.rb:50:in `define'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/schema.rb:46:in `define'
/usr/share/puppet-dashboard/db/schema.rb:13:in `<top (required)>'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:245:in `load_schema'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:266:in `block in load_schema_current'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:265:in `load_schema_current'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:258:in `block (3 levels) in <top (required)>'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:262:in `block (3 levels) in <top (required)>'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli.rb:424:in `exec'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli.rb:18:in `start'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/exe/bundle:30:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/exe/bundle:22:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.2.5/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Mysql2::Error: Can't create table 'dashboard.#sql-59c_5' (errno: 150)
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `_query'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `block in query'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `handle_interrupt'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `query'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:976:in `add_foreign_key'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:871:in `block in method_missing'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `block in say_with_time'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `say_with_time'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:860:in `method_missing'
/usr/share/puppet-dashboard/db/schema.rb:221:in `block in <top (required)>'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/schema.rb:50:in `instance_eval'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/schema.rb:50:in `define'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/schema.rb:46:in `define'
/usr/share/puppet-dashboard/db/schema.rb:13:in `<top (required)>'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:245:in `load_schema'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:266:in `block in load_schema_current'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:265:in `load_schema_current'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:258:in `block (3 levels) in <top (required)>'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:262:in `block (3 levels) in <top (required)>'
/usr/share/puppet-dashboard/vendor/bundle/ruby/2.2.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli.rb:424:in `exec'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/cli.rb:18:in `start'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/exe/bundle:30:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.2.5/gems/bundler-1.16.6/exe/bundle:22:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.5/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.2.5/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)

**Comment by bwitt** [comment]
thanks!  sounds like we need to make `report_id` on table `metrics` have a type of bigint.

**Comment by unixman99** [comment]
ok, until then what would be best workaround?  

Is this correct?  Because i'm getting broken links for the images.

bundle exec rake db:drop RAILS_ENV=production
bundle exec rake db:create RAILS_ENV=production
bundle exec rake db:migrate RAILS_ENV=production

**Comment by ZeroPointEnergy** [comment]
Hmm, I just tried to verify this with a CentOS 7 Vagrant Box but with postgres and db:setup worked. The reason for this seems to be that db:setup loads the db/schema.rb which was generated for postgresql and does not work on MySQL.

So I recomend we remove the db:setup from the installation instructions because it does not work for all the databases.

I started to rework the installation manual while installing it in the box. Currently it is only for Postgres and I have to verify it again. Here is the current version in a temporary branch: https://github.com/ZeroPointEnergy/puppet-dashboard/blob/new-documentation/docs/installation_centos_7.markdown

Your problem with the missing images may come from the fact that in the production environment rails does not serve static files because it assumes that apache or ngnix will do that. You can tell it to serve them by setting:

export RAILS_SERVE_STATIC_FILES=true

**Comment by Absolutelight** [comment]
Hello! I have next issue while starting service by command:

[root@ansible-server-1 puppet-dashboard]# systemctl start puppet-dashboard

**Job for puppet-dashboard.service failed because the control process exited with error code. See "systemctl status puppet-dashboard.service" and "journalctl -xe" for details.**

$ journalctl -xe:

mar 06 04:39:28 server-1 systemd[1]: Failed to start Puppet Dashboard.
-- Subject: Error of unit puppet-dashboard.service
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
...
-- Result: failed.
